export const registerLocator = {
  forgottenForm: '#forgottenFrm',
  forgottenEmailInput: '#forgottenFrm_email',
  forgottenContinueButton: "#forgottenFrm button[title='Continue']",
  errorAlert: '.alert.alert-error, .alert.alert-danger',
  accountForm: '#AccountFrm',
  firstNameInput: '#AccountFrm_firstname',
  lastNameInput: '#AccountFrm_lastname',
  emailInput: '#AccountFrm_email',
  telephoneInput: '#AccountFrm_telephone',
  address1Input: '#AccountFrm_address_1',
  cityInput: '#AccountFrm_city',
  zoneSelect: '#AccountFrm_zone_id',
  postcodeInput: '#AccountFrm_postcode',
  countrySelect: '#AccountFrm_country_id',
  loginNameInput: '#AccountFrm_loginname',
  passwordInput: '#AccountFrm_password',
  confirmPasswordInput: '#AccountFrm_confirm',
  agreeCheckbox: '#AccountFrm_agree',
  registerContinueButton: "#AccountFrm button[title='Continue']",
  mainContainer: '#maincontainer',
} as const;
